export const GET_ALL_POLICIES_REQUEST = 'GET_ALL_POLICIES_REQUEST';
export const GET_ALL_POLICIES_SUCCESS = 'GET_ALL_POLICIES_SUCCESS';
export const GET_ALL_POLICIES_FAILURE = 'GET_ALL_POLICIES_FAILURE';

export const GET_POLICY_BY_ID_REQUEST = 'GET_POLICY_BY_ID_REQUEST';
export const GET_POLICY_BY_ID_SUCCESS = 'GET_POLICY_BY_ID_SUCCESS';
export const GET_POLICY_BY_ID_FAILURE = 'GET_POLICY_BY_ID_FAILURE';

export const CREATE_POLICY_REQUEST = 'CREATE_POLICY_REQUEST';
export const CREATE_POLICY_SUCCESS = 'CREATE_POLICY_SUCCESS';
export const CREATE_POLICY_FAILURE = 'CREATE_POLICY_FAILURE';

export const UPDATE_POLICY_REQUEST = 'UPDATE_POLICY_REQUEST';
export const UPDATE_POLICY_SUCCESS = 'UPDATE_POLICY_SUCCESS';
export const UPDATE_POLICY_FAILURE = 'UPDATE_POLICY_FAILURE';

export const DELETE_POLICY_REQUEST = 'DELETE_POLICY_REQUEST';
export const DELETE_POLICY_SUCCESS = 'DELETE_POLICY_SUCCESS';
export const DELETE_POLICY_FAILURE = 'DELETE_POLICY_FAILURE';