export const GET_AREA_ORDER_REQUEST = 'GET_AREA_ORDER_REQUEST';
export const GET_AREA_ORDER_SUCCESS = 'GET_AREA_ORDER_SUCCESS';
export const GET_AREA_ORDER_FAILURE = 'GET_AREA_ORDER_FAILURE';

// actionType.js
export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE';

export const CALCULATE_ORDER_PRICE_REQUEST = 'CALCULATE_ORDER_PRICE_REQUEST';
export const CALCULATE_ORDER_PRICE_SUCCESS = 'CALCULATE_ORDER_PRICE_SUCCESS';
export const CALCULATE_ORDER_PRICE_FAILURE = 'CALCULATE_ORDER_PRICE_FAILURE';