export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const GET_ALL_STAFF_USER_REQUEST = "GET_ALL_STAFF_USER_REQUEST";
export const GET_ALL_STAFF_USER_SUCCESS = "GET_ALL_STAFF_USER_SUCCESS";
export const GET_ALL_STAFF_USER_FAILURE = "GET_ALL_STAFF_USER_FAILURE";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";
// chưa sử dụng
export const GET_ALL_USER_REQUEST = "GET_ALL_USER_REQUEST";
export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAILURE = "GET_ALL_USER_FAILURE";

export const GET_ALL_STAFF_AND_MANAGER_REQUEST = "GET_ALL_STAFF_AND_MANAGER_REQUEST";
export const GET_ALL_STAFF_AND_MANAGER_SUCCESS = "GET_ALL_STAFF_AND_MANAGER_SUCCESS";
export const GET_ALL_STAFF_AND_MANAGER_FAILURE = "GET_ALL_STAFF_AND_MANAGER_FAILURE";

export const BAN_USER_REQUEST = "BAN_USER_REQUEST";
export const BAN_USER_SUCCESS = "BAN_USER_SUCCESS";
export const BAN_USER_FAILURE = "BAN_USER_FAILURE";

export const GET_ALL_BAN_USER_REQUEST = "GET_ALL_BAN_USER_REQUEST";
export const GET_ALL_BAN_USER_SUCCESS = "GET_ALL_BAN_USER_SUCCESS";
export const GET_ALL_BAN_USER_FAILURE = "GET_ALL_BAN_USER_FAILURE";

export const LOGOUT = "LOGOUT";